<?php

namespace AppBundle\Repository;

use Doctrine\ORM;

/**
 * ForecastsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForecastsRepository extends EntityRepository
{
}
