<?php

namespace AppBundle\Repository;

/**
 * ForecastRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForecastRepository extends \Doctrine\ORM\EntityRepository
{
}
