<?php

namespace AppBundle\Repository;

/**
 * Forecasts_3dRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Forecasts_3dRepository extends \Doctrine\ORM\EntityRepository
{
}
