<?php

namespace AppBundle\Repository;

/**
 * Forecasts_2dRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Forecasts_2dRepository extends \Doctrine\ORM\EntityRepository
{
}
