<?php

namespace AppBundle\Repository;

use Doctrine\ORM;

/**
 * Forecasts5dRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Forecasts5dRepository extends EntityRepository
{
}
