<?php

namespace AppBundle\Repository;

/**
 * Forecasts_5dRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Forecasts_5dRepository extends \Doctrine\ORM\EntityRepository
{
}
