<?php

namespace AppBundle\Repository;

use Doctrine\ORM;

/**
 * Forecasts3dRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Forecasts3dRepository extends EntityRepository
{
}
