<?php

namespace AppBundle\Repository;

/**
 * Forecasts_1dRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Forecasts_1dRepository extends \Doctrine\ORM\EntityRepository
{
}
