weather_app:
    resource: "@AppBundle/Controller/"
    type: annotation
    prefix: /

homepage:
    path:     /
    defaults: { _controller: AppBundle:Home:index }

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    type: yaml

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /account

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
