homepage:
    path:     /
    defaults: { _controller: "AppBundle:Home:index" }

providers:
    path:     /providers/{cityName}
    defaults: { _controller: "AppBundle:Providers:index" }

providers_avg:
    path:     /providers/
    defaults: { _controller: "AppBundle:Providers:show" }

forecast:
    path:     /forecast/{cityName}
    defaults: { _controller: "AppBundle:City:index" }

#weather_app:
#    resource: "@AppBundle/Controller/"
#    type: annotation
#    prefix: /

contacts:
    path:     /contacts
    defaults: { _controller: "AppBundle:Contact:contact" }

api_forecast:
    path:     /api/{apiKey}/forecast
    defaults: { _controller: "AppBundle:Api:fetchForecastJson" }

api_information:
    path:     /info/api
    defaults: { _controller: "AppBundle:Api:showApiHelp" }

graph_display:
    path:     /graph/{cityName}
    defaults: { _controller: "AppBundle:Graph:graphDisplay" }

#Admin section
admin_main:
    path:     /admin
    defaults: { _controller: "AppBundle:Admin/AdminMain:indexAdmin" }
    methods:  [GET]

admin_apis:
    path:     /admin/apis
    defaults: { _controller: "AppBundle:Admin/AdminApi:indexApi" }
    methods:  [GET]

admin_delete_api:
    path:     /admin/delete_api
    defaults: { _controller: "AppBundle:Admin/AdminApi:deleteApiAjax" }
    methods:  [POST]

admin_cities:
    path:     /admin/cities
    defaults: { _controller: "AppBundle:Admin/AdminCity:indexCities" }
    methods:  [GET]

admin_delete_city:
    path:     /admin/delete_city
    defaults: { _controller: "AppBundle:Admin/AdminCity:deleteCityAjax" }
    methods:  [POST]

admin_usage_stats:
    path:     /admin/stats
    defaults: { _controller: "AppBundle:Admin/AdminUsageStats:indexUsageStats" }
    methods:  [GET]

admin_users:
    path:     /admin/users
    defaults: { _controller: "AppBundle:Admin/AdminUser:indexUsers" }
    methods:  [GET]

admin_users_enable:
    path:     /admin/users
    defaults: { _controller: "AppBundle:Admin/AdminUser:enableUserAjax" }
    methods:  [POST]

admin_users_delete:
    path:     /admin/delete_user
    defaults: { _controller: "AppBundle:Admin/AdminUser:deleteUserAjax" }
    methods:  [POST]

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    type: yaml

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /account

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
