# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
          - { name: form.type, alias: app_user_registration }

    app.form.profile:
        class: AppBundle\Form\ProfileType
        tags:
          - { name: form.type, alias: app_user_profile }

    wunderground.crawler.service:
        class: AppBundle\Crawler\WundergroundCrawler
        arguments:
            ["%wunderground_api%"]

    openweathermap.crawler.service:
        class: AppBundle\Crawler\OpenWeatherMapCrawler
        arguments:
            ["%owm_api_key%"]

    app.form.resetting:
        class: AppBundle\Form\ResettingType
        tags:
          - { name: form.type, alias: app_user_resetting }

    app_user.password_resetting:
        class: AppBundle\EventListener\PasswordResettingListener
        arguments: ["@router"]
        tags:
          - {name: kernel.event_subscriber }

    app_user.route_listener:
        class: AppBundle\EventListener\UserRouteListener
        arguments: ["@security.token_storage", "@router"]
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    app_user.registration_confirm:
        class: AppBundle\EventListener\RegistrationsConfirmListener
        arguments: ["@router", "@session"]
        tags:
          - { name: kernel.event_subscriber}

    yahoo.crawler.service:
        class: AppBundle\Crawler\YahooCrawler

    weather.manager.service:
        class: AppBundle\DatabaseManager\WeatherDatabaseManager
        arguments:
            ["@doctrine"]

    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    app.menu.breadcrumb:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu_builder", createBreadcrumbMenu]
        arguments: ["@request_stack"]
        tags:
          - { name: knp_menu.menu, alias: breadcrumb }

    our.provider.service:
        class: AppBundle\DatabaseManager\OurProviderManager
        arguments:
            ["@doctrine"]
