app.index:
    path:     /
    defaults: { _controller: AppBundle:Home:index }

providers:
    path:     /providers/{cityName}
    defaults: { _controller: "AppBundle:Providers:index" }

forecast:
    path:     /forecast/{cityName}
    defaults: { _controller: "AppBundle:City:index" }