AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
             fields: email
             errorPath: email
             message: fos_user.email.already_used
             groups: [ "AppRegistration", "AppProfile" ]


    properties:
        email:
            - NotBlank:
                message: fos_user.email.blank
                groups: [ "AppRegistration", "AppProfile" ]
            - Length:
                min: 2
                minMessage: fos_user.email.short
                max: 255
                maxMessage: fos_user.email.long
                groups: [ "AppRegistration", "AppProfile" ]
            - Email:
                message: fos_user.email.invalid
                groups: ["AppRegistration", "AppProfile" ]
        plainPassword:
            - NotBlank:
                message: fos_user.password.blank
                groups: [ "AppRegistration", "ResetPassword", "ChangePassword" ]
            - Length:
                min: 6
                max: 255
                minMessage: "The password must contain at least {{ limit }} characters."
                maxMessage: "The password cannot be longer than {{ limit }} characters."
                groups: [ "AppRegistration", "AppProfile", "AppReset"]

